
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Oct 09 12:07:14 EDT 2006
//----------------------------------------------------

package edu.umass.cs.flux;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIPE = 8;
  public static final int SESSION = 26;
  public static final int QUESTION = 20;
  public static final int PLUS = 19;
  public static final int EXCLAMATION = 5;
  public static final int LEFT_PAREN = 13;
  public static final int SEMI = 12;
  public static final int RIGHT_SQ_BRACE = 16;
  public static final int STAR = 4;
  public static final int IDENTIFIER = 22;
  public static final int ERROR = 24;
  public static final int COLON = 9;
  public static final int PROGRAM = 25;
  public static final int EQUALS = 11;
  public static final int COMMA = 10;
  public static final int SOURCEDEF = 18;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int TYPEDEF = 17;
  public static final int RIGHT_CR_BRACE = 7;
  public static final int error = 1;
  public static final int ARROW = 3;
  public static final int LEFT_CR_BRACE = 6;
  public static final int RIGHT_PAREN = 14;
  public static final int LEFT_SQ_BRACE = 15;
  public static final int ATOMIC = 2;
  public static final int HANDLE = 23;
}

